version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - $BACK_PORT:8080
    depends_on:
      - db
    environment:
      - PG_USER=$PG_USER
      - PG_PASS=$PG_PASS
      - PG_DB=$PG_DB
      - DB_PORT=$DB_PORT
      - DB_HOST=$DB_HOST
      - PORT=$BACK_PORT
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - $FRONT_PORT:8080
    depends_on:
      - backend
  db:
    image: postgres
    container_name: db
    env_file: .env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASS
      - POSTGRES_DB=$PG_DB
    ports:
      - $DB_PORT:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
